version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432