# Generated by Django 4.0.1 on 2022-04-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='text_en_us',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_en_us',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en_us',
            new_name='title_en',
        ),
    ]
