# Generated by Django 4.0.1 on 2022-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_name_en_us_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
